root: agentic
extends:
   - github.com/wardnet/agentic-stacks/wardnet.yaml@main
skills:
  - ./.agents/skills/bump-rust
  - ./.agents/skills/full-repo-review
agents:
  - ./.agents/agents/rust-engineer
mcp:
  - github.com/pedromvgomes/agentic-toolkit.git/definitions/mcp/chrome-devtools.yaml@main
