//! Build script for `wardnetd`.
//!
//! Derives a SemVer-compliant version string from `git describe` and exposes it
//! as the `WARDNET_VERSION` compile-time environment variable. The OUI lookup
//! table is generated by the `wardnetd-data` crate, which owns the IEEE MA-L
//! CSV database and its code generation.

use std::env;
use std::process::Command;

// Pull in the shared version-parsing helpers so the logic is defined once.
include!("../../build-support/version.rs");

fn main() {
    // Rerun when the git HEAD or any ref changes.
    println!("cargo:rerun-if-changed=../../../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../../../.git/refs/");
    // Rebuild when CALVER is bumped — read_calver() consumes it.
    println!("cargo:rerun-if-changed=../../../../CALVER");
    // Rebuild when the dev overrides flip — local auto-update testing
    // pins the daemon to an older version without touching git tags or
    // CALVER.
    println!("cargo:rerun-if-env-changed=WARDNET_VERSION_OVERRIDE");
    println!("cargo:rerun-if-env-changed=WARDNET_RELEASE_VERSION_OVERRIDE");

    let version = env::var("WARDNET_VERSION_OVERRIDE")
        .ok()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| git_version().unwrap_or_else(cargo_pkg_version));
    println!("cargo:rustc-env=WARDNET_VERSION={version}");

    // Public-facing CalVer. Read straight from CALVER so it stays stable
    // across dev rebuilds (and so docs/openapi.json can't drift commit-by-
    // commit). Override exists for the same "pretend to be an older
    // release" use case as WARDNET_VERSION_OVERRIDE.
    let release_version = env::var("WARDNET_RELEASE_VERSION_OVERRIDE")
        .ok()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(read_calver);
    println!("cargo:rustc-env=WARDNET_RELEASE_VERSION={release_version}");

    // Expose the compile-time target triple so the auto-update runner can
    // map it to the release asset's short arch name (aarch64 / x86_64).
    if let Ok(target) = env::var("TARGET") {
        println!("cargo:rustc-env=WARDNET_TARGET={target}");
    }
}

/// Attempt to derive a version string from `git describe`.
///
/// Returns `None` if git is unavailable or the command fails.
fn git_version() -> Option<String> {
    let output = Command::new("git")
        // `--match v*` is load-bearing: release tags are `v<calver>`, but the
        // repo also carries `edge-v*` tags (ADR-0023) that point at branch
        // commits. Once such a branch merges, an unfiltered `--tags` describe
        // would pick the nearer edge tag, and `parse_git_describe` — which
        // requires a leading `v` — would fall back to a garbage
        // `0.2.0-dev+gedge-v…` version for every dev and CI build.
        .args(["describe", "--tags", "--always", "--dirty", "--match", "v*"])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let describe = String::from_utf8(output.stdout).ok()?.trim().to_owned();
    if describe.is_empty() {
        return None;
    }

    Some(parse_git_describe(&describe))
}
